# Generated by Django 5.2.12 on 2026-04-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound'), ('AUD', 'A$ Australian Dollar'), ('CAD', 'C$ Canadian Dollar'), ('JPY', '¥ Japanese Yen')], default='EUR', max_length=3),
        ),
    ]
